package com.example.archek.vendingmachine;

interface PrefsConst {

    int SETTING_DEFAULT_AMOUNT = 100;
    String SETTINGS_ONES_AMOUNT = "SETTINGS_ONES_AMOUNT";
    String SETTINGS_TWOS_AMOUNT = "SETTINGS_TWOS_AMOUNT";
    String SETTINGS_FIVES_AMOUNT = "SETTINGS_FIVES_AMOUNT";
    String SETTINGS_TENS_AMOUNT = "SETTINGS_TENS_AMOUNT";
}
